[package]
name = "beetry-editor-frontend"
version = "0.1.0"
edition = "2024"

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]

[dependencies]
anyhow.workspace = true
beetry-editor-types = { version = "0.1.0", path = "../beetry-editor-types" }
beetry-plugin = { version = "0.1.0", path = "../beetry-plugin" }
beetry-plugin-types = { version = "0.1.0", path = "../beetry-plugin-types" }
beetry-reconstruction-types = { version = "0.1.0", path = "../beetry-reconstruction-types" }
beetry-serialization = { version = "0.1.0", path = "../beetry-serialization" }
beetry-editor-backend = { version = "0.1.0", path = "../beetry-editor-backend" }
bon.workspace = true
dioxus = { version = "0.7.0", features = [] }
dioxus-logger = "0.7.0"
rfd = { version = "0.15.4", default-features = false, features = [
    "xdg-portal",
    "tokio",
] }
serde.workspace = true
serde-value.workspace = true
