[package]
name = "beetry-editor-frontend"
description = "Internal beetry crate. For the public API, check the beetry crate."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

exclude = ["docs/"]

[dependencies]
anyhow.workspace = true
beetry-message = { version = "0.2.0", path = "../beetry-message" }
beetry-editor-types = { version = "0.2.0", path = "../beetry-editor-types" }
beetry-plugin = { version = "0.2.0", path = "../beetry-plugin" }
beetry-serialization = { version = "0.2.0", path = "../beetry-serialization" }
beetry-editor-backend = { version = "0.2.0", path = "../beetry-editor-backend" }
bon.workspace = true
chrono = "0.4.45"
dioxus = { version = "0.7.10", features = ["desktop"] }
dioxus-logger = "0.7.10"
rfd = { version = "0.17.2", default-features = false, features = [
    "xdg-portal",
] }
serde.workspace = true

[lints]
workspace = true
