[package]
name = "beetry-editor-frontend"
version = "0.1.0"
edition = "2024"
license.workspace = true

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]

[dependencies]
anyhow.workspace = true
beetry-editor-types = { version = "0.1.0", path = "../beetry-editor-types" }
beetry-core = { version = "0.1.0", path = "../beetry-core" }
beetry-plugin = { version = "0.1.0", path = "../beetry-plugin" }
beetry-serialization = { version = "0.1.0", path = "../beetry-serialization" }
beetry-editor-backend = { version = "0.1.0", path = "../beetry-editor-backend" }
bon.workspace = true
chrono = "0.4.42"
dioxus = { version = "0.7.3", features = [] }
dioxus-logger = "0.7.3"
rfd = { version = "0.17.2", default-features = false, features = [
    "xdg-portal",
] }
serde.workspace = true


[lints]
workspace = true
