[workspace]
resolver = "3"
members = [
    "beetry",
    "beetry-channel",
    "beetry-core",
    "beetry-engine",
    "beetry-editor-backend",
    "beetry-editor-frontend",
    "beetry-editor-types",
    "beetry-example",
    "beetry-exec",
    "beetry-macros",
    "beetry-node",
    "beetry-plugin",
    "beetry-reconstruction",
    "beetry-reconstruction-types",
    "beetry-serialization",
]

[workspace.dependencies]
anyhow = "1.0.102"
bon = "3.9.1"
derive_more = { version = "2.1.1", features = ["full"] }
futures = "0.3.32"
getset = "0.1.6"
indexmap = { version = "2.13.0", features = ["serde"] }
mitsein = { version = "0.9.0", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde-value = "0.7.0"
simple-mermaid = "0.2.0"
strum_macros = "0.28.0"
thiserror = "2.0.18"
tracing = "0.1.44"
itertools = "0.14.0"
num-traits = "0.2.19"
tokio = "1.50.0"

[profile.release]
panic = "abort"

[profile.profiling]
inherits = "release"
debug = true

[workspace.package]
license = "MIT"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }

# pedantic
missing_errors_doc = "allow"
must_use_candidate = "allow"

# cherry pick restriction group
assertions_on_result_states = "warn"
cfg_not_test = "warn"
clone_on_ref_ptr = "warn"
dbg_macro = "warn"
doc_include_without_cfg = "warn"
else_if_without_else = "warn"
empty_drop = "deny"
empty_enum_variants_with_brackets = "warn"
empty_structs_with_brackets = "warn"
exit = "deny"
filetype_is_file = "warn"
get_unwrap = "warn"
if_then_some_else_none = "warn"
infinite_loop = "warn"
large_include_file = "warn"
let_underscore_must_use = "warn"
map_with_unused_argument_over_ranges = "warn"
mixed_read_write_in_expression = "warn"
mod_module_files = "deny"
multiple_inherent_impl = "warn"
needless_raw_strings = "warn"
non_zero_suggestions = "warn"
partial_pub_fields = "warn"
print_stderr = "warn"
print_stdout = "warn"
rc_buffer = "warn"
redundant_test_prefix = "warn"
redundant_type_annotations = "warn"
rest_pat_in_fully_bound_structs = "warn"
return_and_then = "warn"
unnecessary_self_imports = "warn"
unneeded_field_pattern = "warn"
unseparated_literal_suffix = "warn"

# cherry pick nursery group
branches_sharing_code = "warn"
clear_with_drain = "warn"
coerce_container_to_any = "warn"
collection_is_never_read = "warn"
fallible_impl_from = "warn"
future_not_send = "warn"
iter_on_single_items = "warn"
iter_with_drain = "warn"
large_stack_frames = "warn"
literal_string_with_formatting_args = "warn"
needless_collect = "warn"
needless_pass_by_ref_mut = "warn"
needless_type_cast = "warn"
non_send_fields_in_send_ty = "warn"
option_if_let_else = "warn"
or_fun_call = "warn"
read_zero_byte_vec = "warn"
redundant_clone = "warn"
redundant_pub_crate = "warn"
search_is_some = "warn"
single_option_map = "warn"
suspicious_operation_groupings = "warn"
trailing_empty_array = "warn"
trait_duplication_in_bounds = "warn"
tuple_array_conversions = "warn"
unnecessary_struct_initialization = "warn"
unused_peekable = "warn"
use_self = "warn"
while_float = "warn"
