[workspace]
resolver = "3"
members = [
    "beetry",
    "beetry-builder",
    "beetry-channel",
    "beetry-core",
    "beetry-editor-backend",
    "beetry-editor-frontend",
    "beetry-editor-launch",
    "beetry-editor-types",
    "beetry-example",
    "beetry-exec",
    "beetry-macros",
    "beetry-node",
    "beetry-plugin",
    "beetry-plugin-types",
    "beetry-reconstruction",
    "beetry-reconstruction-types",
    "beetry-serialization",
]

[workspace.dependencies]
anyhow = "1.0.100"
bon = "3.8.1"
derive_more = { version = "2.0.1", features = ["full"] }
getset = "0.1.6"
indexmap = { version = "2.12.1", features = ["serde"] }
mitsein = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde-value = "0.7.0"
strum_macros = "0.27.2"
thiserror = "2.0.17"
tracing = "0.1.41"
itertools = "0.14.0"
num-traits = "0.2.19"

[profile.release]
panic = "abort"

[profile.profiling]
inherits = "release"
debug = true
