[package]
name = "beetry-reconstruction"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
beetry-builder = { version = "0.1.0", path = "../beetry-builder" }
beetry-channel = { version = "0.1.0", path = "../beetry-channel" }
beetry-core = { version = "0.1.0", path = "../beetry-core" }
beetry-plugin = { version = "0.1.0", path = "../beetry-plugin" }
beetry-reconstruction-types = { version = "0.1.0", path = "../beetry-reconstruction-types" }
beetry-editor-types = { version = "0.1.0", path = "../beetry-editor-types" }
tracing.workspace = true
