[package]
name = "beetry-plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
bon.workspace = true
serde.workspace = true

beetry-core = { version = "0.1.0", path = "../beetry-core" }
beetry-channel = { version = "0.1.0", path = "../beetry-channel" }
beetry-serde = { version = "0.1.0", path = "../beetry-serde" }
inventory = "0.3.21"
serde_json = "1.0.145"
thiserror.workspace = true
