[package]
name = "beetry-plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
bon.workspace = true
serde.workspace = true

beetry-backend = { version = "0.1.0", path = "../beetry-backend" }
beetry-definitions = { version = "0.1.0", path = "../beetry-definitions" }
inventory = "0.3.21"
serde_json = "1.0.145"
