[package]
name = "beetry-exec"
description = "Internal beetry crate. For the public API, check the beetry crate."
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
anyhow.workspace = true
beetry-core = { version = "0.1.0", path = "../beetry-core" }
bon.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["sync", "time", "macros"] }
tracing.workspace = true

[lints]
workspace = true
