[package]
name = "beetry-example"
version = "0.1.0"
edition = "2024"
publish = false
license.workspace = true

[[bin]]
name = "tree_runtime"
path = "src/bin/tree_runtime.rs"

[[bin]]
name = "tree_editing"
path = "src/bin/tree_editing.rs"

[dependencies]
anyhow.workspace = true
beetry = { path = "../beetry" }
bon.workspace = true
mitsein.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
tracing.workspace = true
tracing-subscriber = "0.3.20"
tracing-tree = "0.4.0"
