[package]
name = "beetry-channel"
description = "Beetry library with reusable channel implementations."
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[features]
default = ["tokio"]
tokio = ["dep:tokio"]

[dependencies]
anyhow.workspace = true
beetry-message = { version = "0.1.0", path = "../beetry-message" }
tokio = { workspace = true, features = [
    "sync",
    "time",
    "macros",
], optional = true }
bon.workspace = true
thiserror.workspace = true

[lints]
workspace = true
