[package]
name = "beetry-channel"
version = "0.1.0"
edition = "2024"

[features]
default = ["tokio"]
tokio = ["dep:tokio"]

[dependencies]
anyhow.workspace = true
beetry-core = { version = "0.1.0", path = "../beetry-core" }
tokio = { version = "1.47.1", features = [
    "sync",
    "time",
    "macros",
], optional = true }
bon.workspace = true
