[package]
name = "beetry-node"
version = "0.1.0"
edition = "2024"
license.workspace = true

[features]
default = ["registry"]
registry = [
    "dep:beetry-plugin",
    "dep:beetry-editor-types",
    "dep:mitsein",
    "dep:serde",
]

[dependencies]
beetry-core = { version = "0.1.0", path = "../beetry-core" }
bon.workspace = true
beetry-plugin = { version = "0.1.0", path = "../beetry-plugin", optional = true }
beetry-editor-types = { version = "0.1.0", path = "../beetry-editor-types", optional = true }
mitsein = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
anyhow.workspace = true

[dev-dependencies]
beetry-core = { version = "0.1.0", features = [
    "mock",
], path = "../beetry-core" }

[lints]
workspace = true
