[package]
name = "beetry-node"
version = "0.1.0"
edition = "2024"

[features]
default = ["registry"]
registry = ["dep:beetry-plugin", "dep:beetry-plugin-types"]

[dependencies]
beetry-core = { version = "0.1.0", path = "../beetry-core" }
beetry-plugin = { version = "0.1.0", path = "../beetry-plugin", optional = true }
beetry-plugin-types = { version = "0.1.0", path = "../beetry-plugin-types", optional = true }

[dev-dependencies]
beetry-core = { version = "0.1.0", features = [
    "mock",
], path = "../beetry-core" }
bon.workspace = true
