[package]
name = "beetry-node"
description = "Beetry library with reusable behavior tree nodes."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[features]
default = ["plugin"]
plugin = [
    "dep:beetry-plugin",
    "dep:beetry-editor-types",
    "dep:mitsein",
    "dep:serde",
]

[dependencies]
beetry-core = { version = "0.2.0", path = "../beetry-core" }
bon.workspace = true
beetry-plugin = { version = "0.2.0", path = "../beetry-plugin", optional = true }
beetry-editor-types = { version = "0.2.0", path = "../beetry-editor-types", optional = true }
mitsein = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
anyhow.workspace = true

[dev-dependencies]
beetry-core = { version = "0.2.0", features = [
    "mock",
], path = "../beetry-core" }

[lints]
workspace = true
