[package]
name = "beetry-engine"
description = "Internal beetry crate. For the public API, check the beetry crate."
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[features]
default = []
plugin = ["dep:beetry-node", "dep:beetry-plugin", "dep:beetry-serialization"]

[dependencies]
anyhow.workspace = true
beetry-core = { version = "0.1.0", path = "../beetry-core" }
beetry-editor-types = { version = "0.1.0", path = "../beetry-editor-types" }
beetry-exec = { version = "0.1.0", path = "../beetry-exec" }
beetry-message = { version = "0.1.0", path = "../beetry-message" }
beetry-node = { version = "0.1.0", path = "../beetry-node", optional = true, features = [
    "plugin",
] }
beetry-plugin = { version = "0.1.0", path = "../beetry-plugin", optional = true }
beetry-serialization = { version = "0.1.0", path = "../beetry-serialization", optional = true }
bon.workspace = true
derive_more.workspace = true
futures.workspace = true
getset.workspace = true
itertools.workspace = true
mitsein.workspace = true
rfd = { version = "0.17.2", default-features = false, features = [
    "xdg-portal",
] }
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "sync"] }
tracing.workspace = true

[lints]
workspace = true
