[package]
name = "beetry-editor-launch"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
beetry-editor-frontend = { version = "0.1.0", path = "../beetry-editor-frontend" }
beetry-example = { version = "0.1.0", path = "../beetry-example" }
beetry-node = { version = "0.1.0", path = "../beetry-node", features = [
    "registry",
] }
