[package]
name = "beetry-editor-types"
description = "Internal beetry crate. For the public API, check the beetry crate."
version = "0.1.0"
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
anyhow.workspace = true
beetry-message = { version = "0.1.0", path = "../beetry-message" }
bon.workspace = true
derive_more.workspace = true
getset.workspace = true
indexmap.workspace = true
mitsein.workspace = true
num-traits.workspace = true
schemars.workspace = true
serde.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
