[package]
name = "beetry-editor-types"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
beetry-plugin-types = { version = "0.1.0", path = "../beetry-plugin-types" }
beetry-reconstruction-types = { version = "0.1.0", path = "../beetry-reconstruction-types" }
bon.workspace = true
getset.workspace = true
indexmap.workspace = true
serde.workspace = true
tracing.workspace = true
