[package]
name = "beetry-message"
description = "Internal beetry crate. For the public API, check the beetry crate."
version = "0.1.0"
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
getset.workspace = true
schemars.workspace = true
serde.workspace = true
type_hash = "0.3.0"

[lints]
workspace = true
