[package]
name = "beetry-editor"
version = "0.1.0"
edition = "2024"

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]

[dependencies]
anyhow.workspace = true
beetry-core = { version = "0.1.0", path = "../beetry-core" }
beetry-plugin = { version = "0.1.0", path = "../beetry-plugin" }
beetry-serde = { version = "0.1.0", path = "../beetry-serde" }
beetry-serialization = { version = "0.1.0", path = "../beetry-serialization" }
bon.workspace = true
delegate = "0.13.5"
derive_more.workspace = true
dioxus = { version = "0.7.0", features = [] }
dioxus-logger = "0.7.0"
getset.workspace = true
indexmap = "2.11.3"
itertools.workspace = true
num-traits.workspace = true
rfd = { version = "0.15.4", default-features = false, features = [
    "xdg-portal",
    "tokio",
] }
serde.workspace = true
serde-value.workspace = true
slotmap = "1.0.7"
tracing.workspace = true
