[package]
name = "beetry"
description = "Behavior tree framework with a runtime, plugin system, and Beehive editor."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[features]
default = ["plugin", "editor", "tokio"]
plugin = [
    "dep:beetry-plugin",
    "dep:beetry-channel",
    "beetry-engine/plugin",
    "beetry-node/plugin",
]
editor = ["plugin", "dep:beetry-editor-frontend"]
tokio = ["beetry-channel/tokio"]

[dependencies]
beetry-channel = { version = "0.2.0", path = "../beetry-channel", optional = true }
beetry-core = { version = "0.2.0", path = "../beetry-core" }
beetry-engine = { version = "0.2.0", path = "../beetry-engine" }
beetry-editor-frontend = { version = "0.2.0", path = "../beetry-editor-frontend", optional = true }
beetry-node = { version = "0.2.0", path = "../beetry-node" }
beetry-macros = { version = "0.2.0", path = "../beetry-macros" }
beetry-message = { version = "0.2.0", path = "../beetry-message" }
beetry-plugin = { version = "0.2.0", path = "../beetry-plugin", optional = true }

[lints]
workspace = true
