use crate::TickStatus;
use mitsein::vec1::Vec1;

#[cfg_attr(any(test, feature = "mock"), mockall::automock)]
pub trait Node {
    fn tick(&mut self) -> TickStatus;
    /// Reset given node to its default state:
    /// - should only be called by the behavior tree (root)
    /// - should not block the thread and ideally be finished during single tick
    fn reset(&mut self) {}

    /// Interface to abort/cancel running tasks. Signal is generated by scheduling (non-leaf)
    /// nodes and propagated to children. If leaf node's task is running in an executor an abort signal is sent.
    fn abort(&mut self) {}
}

pub type BoxNode = Box<dyn Node>;

impl Node for BoxNode {
    fn tick(&mut self) -> TickStatus {
        (**self).tick()
    }

    fn reset(&mut self) {
        (**self).reset();
    }

    fn abort(&mut self) {
        (**self).abort();
    }
}

pub type NonEmptyNodes = Vec1<BoxNode>;
