[package]
name = "beetry-macros"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.106"
quote = "1.0.44"
syn = { version = "2.0.116", features = ["full"] }
bon.workspace = true

[dev-dependencies]
beetry-core = { version = "0.1.0", path = "../beetry-core" }
beetry-channel = { version = "0.1.0", path = "../beetry-channel" }
