[package]
name = "beetry-macros"
description = "Internal beetry crate. For the public API, check the beetry crate."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro-error2 = "2.0.1"
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.3", features = ["full"] }
bon.workspace = true

[dev-dependencies]
beetry-core = { version = "0.2.0", path = "../beetry-core" }
beetry-channel = { version = "0.2.0", path = "../beetry-channel" }

[lints]
workspace = true
