[package]
name = "beetry-editor-backend"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
anyhow.workspace = true
beetry-core = { version = "0.1.0", path = "../beetry-core" }
beetry-editor-types = { version = "0.1.0", path = "../beetry-editor-types" }
mitsein.workspace = true
num-traits.workspace = true
tracing.workspace = true

[dev-dependencies]
rstest = "0.26.1"

[lints]
workspace = true
