[package]
name = "beetry-editor-backend"
description = "Internal beetry crate. For the public API, check the beetry crate."
version = "0.1.0"
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
anyhow.workspace = true
beetry-editor-types = { version = "0.1.0", path = "../beetry-editor-types" }
embed-doc-image = "0.1.4"
mitsein.workspace = true
num-traits.workspace = true
tracing.workspace = true

[dev-dependencies]
beetry-message = { version = "0.1.0", path = "../beetry-message" }
rstest = "0.26.1"
type_hash = "0.3.0"

[lints]
workspace = true
