[book]
title = "Beetry 🐝🌳"
authors = ["Adrian"]
language = "en"

[rust]
edition = "2024"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.playground]
runnable = false
