[package]
name = "beetry-core"
version = "0.1.0"
edition = "2024"

[features]
default = []
mock = ["dep:mockall"]

[dependencies]
anyhow.workspace = true
bon.workspace = true
mitsein.workspace = true
mockall = { version = "0.13.1", optional = true }
serde.workspace = true
state-shift = "2.1.1"
thiserror.workspace = true
tokio = { version = "1.47.1", features = ["sync", "time", "macros"] }
tracing.workspace = true

[dev-dependencies]
mockall = { version = "0.13.1" }
