[package]
name = "beetry-core"
version = "0.1.0"
edition = "2024"

[features]
default = []
mock = ["dep:mockall"]

[dependencies]
anyhow.workspace = true
bon.workspace = true
futures.workspace = true
mitsein.workspace = true
mockall = { version = "0.14.0", optional = true }
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "time", "macros"] }
tracing.workspace = true

[dev-dependencies]
mockall = { version = "0.14.0" }
tokio = { workspace = true, features = ["rt"] }
