name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
  # Rust toolchain is installed by default
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: >
        sudo apt update &&
        sudo apt install -y 
        libwebkit2gtk-4.1-dev 
        build-essential 
        curl
        wget
        file
        libxdo-dev
        libssl-dev
        libayatana-appindicator3-dev
        librsvg2-dev

    - uses: Swatinem/rust-cache@v2
    - name: Check
      run: cargo check
    - name: Run tests
      run: cargo test
    - name: Cargo deny
      run: >
        cargo install cargo-deny --locked &&
        cargo deny check advisories licenses bans sources
